### ISSUE TITLE
with v1.1.1, simple metric visualization is not working.

### ISSUE THREAD

**Issue by ttgile** [datasweet/kibana-datasweet-formula#29]
Hi,

I'm using kibana 6.3.2 and i downloaded and installed the datasweet-formula v1.1.1.
When i tried to create a simple metric visualization it didn't work.
Only when i reverted to v1.1.0 the visualization worked as expected.
Any idea?

Regards

**Comment by tcharlot-datasweet** [comment]
Hi @ttgile , 
Actually we are discussing with team about the change by @gmatheus for the version v6.4
I will take a look
Thx for your report.

**Comment by ttgile** [comment]
Hi,

Many thanks for the fast response.
I just downloaded the new zip and now it seems that the kibana-plugin installation fails while doing the optimization:

Attempting to transfer from file:///opt/installation/kibana/kibana-datasweet-formula-1.1.2.zip
Transferring 12510190 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false --uiSettings.enabled=false
(node:6980) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL { Error: Optimizations failure.
   6191 modules

    ERROR in ./plugins/datasweet_formula/public/decorators/lib/formula_parser.js
    Module not found: Error: Can't resolve 'expr-eval' in '/usr/share/kibana/plugins/datasweet_formula/public/decorators/lib'

    ERROR in ./plugins/datasweet_formula/public/formulas/percentile.js
    Module not found: Error: Can't resolve 'percentile' in '/usr/share/kibana/plugins/datasweet_formula/public/formulas'

    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:245:27)
    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:28:26)
    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:241:12)
    at applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:671:19)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:662:11)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/usr/share/kibana/node_modules/webpack/lib/BannerPlugin.js:67:5)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:657:10)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/usr/share/kibana/node_modules/extract-text-webpack-plugin/dist/index.js:275:11)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:653:9)
  cause:
   { Error: Optimizations failure.
   6191 modules

Regards

**Comment by ttgile** [comment]
Hi,

Please notice that since i got the above error, i'm still using v1.1.0.
We found another issue with this release: it appears that Min/Max aggregations are breaking the visualization when there is no data according to the time filter.

Regards

**Comment by lfroment-datasweet** [comment]
Hi @ttgile ,

could you please give us a screenshot. Are you talking about Kibana's built in Min/Max aggs ?

**Comment by ttgile** [comment]
Hi,

Sorry for missing the example, 
It appears that the issue occurs when the datasweet formula is part of the visualization.
In the below example, you can see that i create metriv visualization with 3 aggregation:
1. Count
2. Max
3. datasweet related on agg1 only

when using all aggregations when there is data retrieved for the requested time all works fine.
when using all aggregations when there i no data for the requested time, the visualization doesn't work.
when disabling the Max aggregation, only (agg2), the visualization works.
when disabling the datasweet formula only (agg3) the visualization works.

Below screenshot shows the visualization works with agg2 disabled:
![image](https://user-images.githubusercontent.com/44156653/47589884-3648b080-d973-11e8-9061-3cb3773d6b19.png)

Below screenshot shows the visualization exception when agg2 is enabled:
![image](https://user-images.githubusercontent.com/44156653/47589998-90e20c80-d973-11e8-89b1-3edd621fe9bb.png)

Regards

**Comment by tcharlot-datasweet** [comment]
Hi @ttgile,

i tried to install the plugin from a fresh kibana, its seems OK.
Did you remove the old plugin first with `kibana-plugin remove datasweet_formula`

Here the install from 6.3.2
`tcharlot@tcharlot-linux:~/Téléchargements/kibana-6.3.2-linux-x86_64/bin$ ./kibana-plugin install file:///home/tcharlot/Téléchargements/datasweet_formula-1.1.2_kibana-6.3.2.zip 
Attempting to transfer from file:///home/tcharlot/Téléchargements/datasweet_formula-1.1.2_kibana-6.3.2.zip
Transferring 407732 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
`

For the bug, i can reproduce with version 1.1.2

**Comment by ttgile** [comment]
Hi @tcharlot-datasweet,

Many thanks for your response and for the fix.
unfortunately, I'm still getting the same exception exception when trying to install either v1.1.2 or v1.1.3 (I verified i remove the old plugin before).
Installing v1.1.0 or v1.1.1 works fine.
I will try to figure out the issue, it might be related to other plugin i'm using.

Thanks & Regards...
